version: '3.1'

services:
  oauth:
    image: server
    build: ./server
    ports:
    - "8081:8081"
    networks:
      - commons-api
    container_name: oauth-server
  client:
    image: client
    build: ./client
    ports:
    - "8082:8082"
    networks:
      - commons-api
    depends_on:      
      - oauth
    container_name: web-client


networks:
  commons-api:
    driver: bridge